# Generated by Django 3.2.12 on 2022-03-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.TextField(unique=True)),
                ('avatar_url', models.TextField(blank=True, max_length=100)),
                ('title', models.TextField(blank=True, max_length=100, unique=True)),
                ('html_url', models.TextField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(blank=True)),
            ],
        ),
    ]
