# Generated by Django 3.2.12 on 2022-03-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='title',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
