# Generated by Django 3.2.12 on 2022-03-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0002_alter_issues_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='score',
            field=models.TextField(blank=True),
        ),
    ]
