# Generated by Django 3.2.12 on 2022-03-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0003_alter_issues_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issues',
            new_name='Issue',
        ),
    ]
