# Generated by Django 3.2.12 on 2022-03-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0004_rename_issues_issue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issue',
            new_name='Issues',
        ),
    ]
