# Generated by Django 3.2.12 on 2022-03-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0007_rename_issue_issues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issues',
            new_name='Issue',
        ),
    ]
