# Generated by Django 3.2.12 on 2022-03-04 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0011_alter_issue_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='description',
            new_name='descrip',
        ),
    ]
